# Generated by Django 5.0 on 2025-04-22 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIncidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Incidencia',
                'verbose_name_plural': 'Tipo de Incidencias',
            },
        ),
        migrations.CreateModel(
            name='SolicitudSoporte',
            fields=[
                ('ticket', models.AutoField(primary_key=True, serialize=False)),
                ('caso_usuario', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_incidencia', to='casos.tipoincidencia')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
            },
        ),
    ]
