# Generated by Django 5.0 on 2025-05-02 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTecnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=255)),
                ('tecnico', models.CharField(max_length=255)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feedback_tecnico', to='casos.solicitudsoporte')),
            ],
        ),
    ]
