# Generated by Django 4.2 on 2025-02-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_remove_solicitudsoporte_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='ticket',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
