# Generated by Django 5.0 on 2025-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0003_feedbacktecnico_fecha_creacion_historialestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestado',
            name='comentario',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='feedback tecnico'),
        ),
    ]
