# Generated by Django 5.0 on 2025-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0004_alter_historialestado_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudsoporte',
            name='ticket_custom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
