# Generated by Django 5.0 on 2025-06-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0005_solicitudsoporte_ticket_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='ticket_custom',
            field=models.IntegerField(null=True),
        ),
    ]
