# Generated by Django 5.0 on 2025-06-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0006_alter_solicitudsoporte_ticket_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsoporte',
            name='ticket_custom',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
