# Generated by Django 5.0 on 2025-06-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0007_alter_solicitudsoporte_ticket_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudsoporte',
            name='ticket_custom',
        ),
    ]
