# Generated by Django 5.0 on 2025-06-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0008_remove_solicitudsoporte_ticket_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestado',
            name='usuario',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
