# Generated by Django 5.0 on 2025-06-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0009_historialestado_comentario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialestado',
            name='comentario_usuario',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
