# Generated by Django 5.0 on 2025-06-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0010_alter_historialestado_comentario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialestado',
            name='comentario_usuario',
        ),
        migrations.AddField(
            model_name='historialestado',
            name='usuario_feedback',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
