# Generated by Django 5.0 on 2025-06-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0011_remove_historialestado_comentario_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialestado',
            old_name='usuario_feedback',
            new_name='usuario',
        ),
    ]
