# Generated by Django 5.0 on 2025-06-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0009_historialestado_usuario'),
        ('casos', '0012_rename_usuario_feedback_historialestado_usuario'),
    ]

    operations = [
    ]
