# Generated by Django 5.0 on 2025-06-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0013_merge_20250606_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudsoporte',
            name='ticket_tilena',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
