# Generated by Django 5.0 on 2025-06-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0014_solicitudsoporte_ticket_tilena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialestado',
            name='usuario',
        ),
    ]
