# Generated by Django 5.0 on 2025-06-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0015_remove_historialestado_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestado',
            name='usuario',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
