# Generated by Django 5.0 on 2025-06-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0016_historialestado_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackTecnico',
        ),
    ]
