# Generated by Django 5.0 on 2025-05-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_usuario_usuarioem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioem',
            options={},
        ),
        migrations.AlterModelTable(
            name='usuarioem',
            table='usuarios_usuarioem',
        ),
    ]
