# Generated by Django 5.0 on 2025-05-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuarioem_options_alter_usuarioem_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioEm',
        ),
    ]
