# Generated by Django 5.0 on 2025-05-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuarioem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioEm',
        ),
    ]
