# Generated by Django 5.0 on 2025-06-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_datosusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipouser',
            name='tipo',
            field=models.CharField(choices=[('1', 'Tecnico'), ('2', 'operativo'), ('3', 'administrador'), ('4', 'directivo')], default=2, max_length=20),
        ),
    ]
